apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: persons-finder
  namespace: persons-finder
  labels:
    app.kubernetes.io/name: persons-finder
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: persons-finder
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health/readiness
    # TLS termination at ALB using ACM certificate
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}, {"HTTP": 80}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:637423556985:certificate/REPLACE-WITH-CERT-ID"
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: persons-finder
                port:
                  number: 80
