apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: persons-finder
  namespace: persons-finder
  labels:
    app.kubernetes.io/name: persons-finder
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: persons-finder
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: persons-finder
