apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: persons-finder
  namespace: persons-finder
  labels:
    app: persons-finder
    app.kubernetes.io/name: persons-finder
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: persons-finder
spec:
  selector:
    matchLabels:
      app: persons-finder
  endpoints:
    - port: management
      path: /actuator/prometheus
      interval: 15s
